/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AnalyticsGenericEvent model module.
 * @module snapser-apis/AnalyticsGenericEvent
 * @version cremebrulee: v1 SDK
 */
class AnalyticsGenericEvent {
    /**
     * Constructs a new <code>AnalyticsGenericEvent</code>.
     * @alias module:snapser-apis/AnalyticsGenericEvent
     * @param event {String} Event to be added
     * @param id {Number} Order in which events will be ingested
     */
    constructor(event, id) { 
        
        AnalyticsGenericEvent.initialize(this, event, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, event, id) { 
        obj['event'] = event;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>AnalyticsGenericEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/AnalyticsGenericEvent} obj Optional instance to populate.
     * @return {module:snapser-apis/AnalyticsGenericEvent} The populated <code>AnalyticsGenericEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnalyticsGenericEvent();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], {'String': 'String'});
            }
            if (data.hasOwnProperty('time_offset')) {
                obj['time_offset'] = ApiClient.convertToType(data['time_offset'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AnalyticsGenericEvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AnalyticsGenericEvent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AnalyticsGenericEvent.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['event'] && !(typeof data['event'] === 'string' || data['event'] instanceof String)) {
            throw new Error("Expected the field `event` to be a primitive type in the JSON string but got " + data['event']);
        }

        return true;
    }


}

AnalyticsGenericEvent.RequiredProperties = ["event", "id"];

/**
 * Epoch timestamp of event in seconds, if this and offset are not provided, it will be the request time
 * @member {Number} created_at
 */
AnalyticsGenericEvent.prototype['created_at'] = undefined;

/**
 * Event to be added
 * @member {String} event
 */
AnalyticsGenericEvent.prototype['event'] = undefined;

/**
 * Order in which events will be ingested
 * @member {Number} id
 */
AnalyticsGenericEvent.prototype['id'] = undefined;

/**
 * Key value pairs of the properties
 * @member {Object.<String, String>} properties
 */
AnalyticsGenericEvent.prototype['properties'] = undefined;

/**
 * Time offset in seconds with server time
 * @member {Number} time_offset
 */
AnalyticsGenericEvent.prototype['time_offset'] = undefined;






export default AnalyticsGenericEvent;

