/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthAnonLoginRequest model module.
 * @module snapser-apis/AuthAnonLoginRequest
 * @version cremebrulee: v1 SDK
 */
class AuthAnonLoginRequest {
    /**
     * Constructs a new <code>AuthAnonLoginRequest</code>.
     * @alias module:snapser-apis/AuthAnonLoginRequest
     * @param username {String} User's login ID
     */
    constructor(username) { 
        
        AuthAnonLoginRequest.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>AuthAnonLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/AuthAnonLoginRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/AuthAnonLoginRequest} The populated <code>AuthAnonLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthAnonLoginRequest();

            if (data.hasOwnProperty('create_user')) {
                obj['create_user'] = ApiClient.convertToType(data['create_user'], 'Boolean');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthAnonLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthAnonLoginRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthAnonLoginRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }

        return true;
    }


}

AuthAnonLoginRequest.RequiredProperties = ["username"];

/**
 * Whether to create a user, if it does not exist
 * @member {Boolean} create_user
 */
AuthAnonLoginRequest.prototype['create_user'] = undefined;

/**
 * User's login ID
 * @member {String} username
 */
AuthAnonLoginRequest.prototype['username'] = undefined;






export default AuthAnonLoginRequest;

