/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The AuthGoogleLoginRequest model module.
 * @module snapser-apis/AuthGoogleLoginRequest
 * @version cremebrulee: v1 SDK
 */
class AuthGoogleLoginRequest {
    /**
     * Constructs a new <code>AuthGoogleLoginRequest</code>.
     * @alias module:snapser-apis/AuthGoogleLoginRequest
     * @param token {String} Google IDtoken generated on the client
     */
    constructor(token) { 
        
        AuthGoogleLoginRequest.initialize(this, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token) { 
        obj['token'] = token;
    }

    /**
     * Constructs a <code>AuthGoogleLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/AuthGoogleLoginRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/AuthGoogleLoginRequest} The populated <code>AuthGoogleLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthGoogleLoginRequest();

            if (data.hasOwnProperty('create_user')) {
                obj['create_user'] = ApiClient.convertToType(data['create_user'], 'Boolean');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthGoogleLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthGoogleLoginRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthGoogleLoginRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}

AuthGoogleLoginRequest.RequiredProperties = ["token"];

/**
 * Whether to create a user, if it does not exist
 * @member {Boolean} create_user
 */
AuthGoogleLoginRequest.prototype['create_user'] = undefined;

/**
 * Google IDtoken generated on the client
 * @member {String} token
 */
AuthGoogleLoginRequest.prototype['token'] = undefined;






export default AuthGoogleLoginRequest;

