/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import LeaderboardsTier from './LeaderboardsTier.js';

/**
 * The LeaderboardsIncrementScoreResponse model module.
 * @module snapser-apis/LeaderboardsIncrementScoreResponse
 * @version cremebrulee: v1 SDK
 */
class LeaderboardsIncrementScoreResponse {
    /**
     * Constructs a new <code>LeaderboardsIncrementScoreResponse</code>.
     * @alias module:snapser-apis/LeaderboardsIncrementScoreResponse
     */
    constructor() { 
        
        LeaderboardsIncrementScoreResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeaderboardsIncrementScoreResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/LeaderboardsIncrementScoreResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/LeaderboardsIncrementScoreResponse} The populated <code>LeaderboardsIncrementScoreResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaderboardsIncrementScoreResponse();

            if (data.hasOwnProperty('rank')) {
                obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('tier')) {
                obj['tier'] = LeaderboardsTier.constructFromObject(data['tier']);
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeaderboardsIncrementScoreResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeaderboardsIncrementScoreResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `tier`
        if (data['tier']) { // data not null
          LeaderboardsTier.validateJSON(data['tier']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }

        return true;
    }


}



/**
 * Latest rank to be returned
 * @member {Number} rank
 */
LeaderboardsIncrementScoreResponse.prototype['rank'] = undefined;

/**
 * Incremented score to be returned
 * @member {Number} score
 */
LeaderboardsIncrementScoreResponse.prototype['score'] = undefined;

/**
 * @member {module:snapser-apis/LeaderboardsTier} tier
 */
LeaderboardsIncrementScoreResponse.prototype['tier'] = undefined;

/**
 * User ID of the user
 * @member {String} user_id
 */
LeaderboardsIncrementScoreResponse.prototype['user_id'] = undefined;






export default LeaderboardsIncrementScoreResponse;

