/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LeaderboardsUserScore from './LeaderboardsUserScore';

/**
 * The LeaderboardsTieredUserScore model module.
 * @module snapser-apis/LeaderboardsTieredUserScore
 * @version cremebrulee: v1 SDK
 */
class LeaderboardsTieredUserScore {
    /**
     * Constructs a new <code>LeaderboardsTieredUserScore</code>.
     * @alias module:snapser-apis/LeaderboardsTieredUserScore
     */
    constructor() { 
        
        LeaderboardsTieredUserScore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeaderboardsTieredUserScore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/LeaderboardsTieredUserScore} obj Optional instance to populate.
     * @return {module:snapser-apis/LeaderboardsTieredUserScore} The populated <code>LeaderboardsTieredUserScore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaderboardsTieredUserScore();

            if (data.hasOwnProperty('tier')) {
                obj['tier'] = ApiClient.convertToType(data['tier'], 'String');
            }
            if (data.hasOwnProperty('user_score')) {
                obj['user_score'] = LeaderboardsUserScore.constructFromObject(data['user_score']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeaderboardsTieredUserScore</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeaderboardsTieredUserScore</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tier'] && !(typeof data['tier'] === 'string' || data['tier'] instanceof String)) {
            throw new Error("Expected the field `tier` to be a primitive type in the JSON string but got " + data['tier']);
        }
        // validate the optional field `user_score`
        if (data['user_score']) { // data not null
          LeaderboardsUserScore.validateJSON(data['user_score']);
        }

        return true;
    }


}



/**
 * Name of the tier
 * @member {String} tier
 */
LeaderboardsTieredUserScore.prototype['tier'] = undefined;

/**
 * @member {module:snapser-apis/LeaderboardsUserScore} user_score
 */
LeaderboardsTieredUserScore.prototype['user_score'] = undefined;






export default LeaderboardsTieredUserScore;

