/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LeaderboardsTier from './LeaderboardsTier';
import LeaderboardsUserScore from './LeaderboardsUserScore';

/**
 * The LeaderboardsGetScoresResponse model module.
 * @module snapser-apis/LeaderboardsGetScoresResponse
 * @version cremebrulee: v1 SDK
 */
class LeaderboardsGetScoresResponse {
    /**
     * Constructs a new <code>LeaderboardsGetScoresResponse</code>.
     * @alias module:snapser-apis/LeaderboardsGetScoresResponse
     */
    constructor() { 
        
        LeaderboardsGetScoresResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeaderboardsGetScoresResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/LeaderboardsGetScoresResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/LeaderboardsGetScoresResponse} The populated <code>LeaderboardsGetScoresResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaderboardsGetScoresResponse();

            if (data.hasOwnProperty('tier')) {
                obj['tier'] = LeaderboardsTier.constructFromObject(data['tier']);
            }
            if (data.hasOwnProperty('user_scores')) {
                obj['user_scores'] = ApiClient.convertToType(data['user_scores'], [LeaderboardsUserScore]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeaderboardsGetScoresResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeaderboardsGetScoresResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `tier`
        if (data['tier']) { // data not null
          LeaderboardsTier.validateJSON(data['tier']);
        }
        if (data['user_scores']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['user_scores'])) {
                throw new Error("Expected the field `user_scores` to be an array in the JSON data but got " + data['user_scores']);
            }
            // validate the optional field `user_scores` (array)
            for (const item of data['user_scores']) {
                LeaderboardsUserScore.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:snapser-apis/LeaderboardsTier} tier
 */
LeaderboardsGetScoresResponse.prototype['tier'] = undefined;

/**
 * List of users in the order defined by the leaderboard
 * @member {Array.<module:snapser-apis/LeaderboardsUserScore>} user_scores
 */
LeaderboardsGetScoresResponse.prototype['user_scores'] = undefined;






export default LeaderboardsGetScoresResponse;

