/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatisticsSetUserStatisticRequest from './StatisticsSetUserStatisticRequest';

/**
 * The StatisticsBatchSetUserStatisticsRequest model module.
 * @module snapser-apis/StatisticsBatchSetUserStatisticsRequest
 * @version cremebrulee: v1 SDK
 */
class StatisticsBatchSetUserStatisticsRequest {
    /**
     * Constructs a new <code>StatisticsBatchSetUserStatisticsRequest</code>.
     * @alias module:snapser-apis/StatisticsBatchSetUserStatisticsRequest
     * @param requests {Array.<module:snapser-apis/StatisticsSetUserStatisticRequest>} Array of operations to be performed
     */
    constructor(requests) { 
        
        StatisticsBatchSetUserStatisticsRequest.initialize(this, requests);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requests) { 
        obj['requests'] = requests;
    }

    /**
     * Constructs a <code>StatisticsBatchSetUserStatisticsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StatisticsBatchSetUserStatisticsRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/StatisticsBatchSetUserStatisticsRequest} The populated <code>StatisticsBatchSetUserStatisticsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsBatchSetUserStatisticsRequest();

            if (data.hasOwnProperty('requests')) {
                obj['requests'] = ApiClient.convertToType(data['requests'], [StatisticsSetUserStatisticRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsBatchSetUserStatisticsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsBatchSetUserStatisticsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StatisticsBatchSetUserStatisticsRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['requests']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['requests'])) {
                throw new Error("Expected the field `requests` to be an array in the JSON data but got " + data['requests']);
            }
            // validate the optional field `requests` (array)
            for (const item of data['requests']) {
                StatisticsSetUserStatisticRequest.validateJSON(item);
            };
        }

        return true;
    }


}

StatisticsBatchSetUserStatisticsRequest.RequiredProperties = ["requests"];

/**
 * Array of operations to be performed
 * @member {Array.<module:snapser-apis/StatisticsSetUserStatisticRequest>} requests
 */
StatisticsBatchSetUserStatisticsRequest.prototype['requests'] = undefined;






export default StatisticsBatchSetUserStatisticsRequest;

