/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatisticsGetUserStatisticsRequest from './StatisticsGetUserStatisticsRequest';
import StatisticsUserStatistic from './StatisticsUserStatistic';

/**
 * The StatisticsBatchGetUserStatisticsSingleResponse model module.
 * @module snapser-apis/StatisticsBatchGetUserStatisticsSingleResponse
 * @version cremebrulee: v1 SDK
 */
class StatisticsBatchGetUserStatisticsSingleResponse {
    /**
     * Constructs a new <code>StatisticsBatchGetUserStatisticsSingleResponse</code>.
     * @alias module:snapser-apis/StatisticsBatchGetUserStatisticsSingleResponse
     */
    constructor() { 
        
        StatisticsBatchGetUserStatisticsSingleResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatisticsBatchGetUserStatisticsSingleResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StatisticsBatchGetUserStatisticsSingleResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/StatisticsBatchGetUserStatisticsSingleResponse} The populated <code>StatisticsBatchGetUserStatisticsSingleResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsBatchGetUserStatisticsSingleResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = StatisticsGetUserStatisticsRequest.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], [StatisticsUserStatistic]);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsBatchGetUserStatisticsSingleResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsBatchGetUserStatisticsSingleResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `request`
        if (data['request']) { // data not null
          StatisticsGetUserStatisticsRequest.validateJSON(data['request']);
        }
        if (data['response']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['response'])) {
                throw new Error("Expected the field `response` to be an array in the JSON data but got " + data['response']);
            }
            // validate the optional field `response` (array)
            for (const item of data['response']) {
                StatisticsUserStatistic.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} message
 */
StatisticsBatchGetUserStatisticsSingleResponse.prototype['message'] = undefined;

/**
 * @member {module:snapser-apis/StatisticsGetUserStatisticsRequest} request
 */
StatisticsBatchGetUserStatisticsSingleResponse.prototype['request'] = undefined;

/**
 * @member {Array.<module:snapser-apis/StatisticsUserStatistic>} response
 */
StatisticsBatchGetUserStatisticsSingleResponse.prototype['response'] = undefined;

/**
 * @member {Boolean} success
 */
StatisticsBatchGetUserStatisticsSingleResponse.prototype['success'] = undefined;






export default StatisticsBatchGetUserStatisticsSingleResponse;

