/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The StorageUserCounterResponse model module.
 * @module snapser-apis/StorageUserCounterResponse
 * @version cremebrulee: v1 SDK
 */
class StorageUserCounterResponse {
    /**
     * Constructs a new <code>StorageUserCounterResponse</code>.
     * @alias module:snapser-apis/StorageUserCounterResponse
     * @param count {Number} Value of the counter
     */
    constructor(count) { 
        
        StorageUserCounterResponse.initialize(this, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count) { 
        obj['count'] = count;
    }

    /**
     * Constructs a <code>StorageUserCounterResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StorageUserCounterResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/StorageUserCounterResponse} The populated <code>StorageUserCounterResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageUserCounterResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageUserCounterResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageUserCounterResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StorageUserCounterResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['owner_id'] && !(typeof data['owner_id'] === 'string' || data['owner_id'] instanceof String)) {
            throw new Error("Expected the field `owner_id` to be a primitive type in the JSON string but got " + data['owner_id']);
        }

        return true;
    }


}

StorageUserCounterResponse.RequiredProperties = ["count"];

/**
 * Value of the counter
 * @member {Number} count
 */
StorageUserCounterResponse.prototype['count'] = undefined;

/**
 * Counter owner's user ID
 * @member {String} owner_id
 */
StorageUserCounterResponse.prototype['owner_id'] = undefined;






export default StorageUserCounterResponse;

