/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StorageBatchGetAppendBlobsSingleResponse from './StorageBatchGetAppendBlobsSingleResponse';
import StorageUserAppendBlobResponse from './StorageUserAppendBlobResponse';

/**
 * The StorageBatchGetAppendBlobsResponse model module.
 * @module snapser-apis/StorageBatchGetAppendBlobsResponse
 * @version cremebrulee: v1 SDK
 */
class StorageBatchGetAppendBlobsResponse {
    /**
     * Constructs a new <code>StorageBatchGetAppendBlobsResponse</code>.
     * @alias module:snapser-apis/StorageBatchGetAppendBlobsResponse
     */
    constructor() { 
        
        StorageBatchGetAppendBlobsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageBatchGetAppendBlobsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StorageBatchGetAppendBlobsResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/StorageBatchGetAppendBlobsResponse} The populated <code>StorageBatchGetAppendBlobsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageBatchGetAppendBlobsResponse();

            if (data.hasOwnProperty('append_blobs')) {
                obj['append_blobs'] = ApiClient.convertToType(data['append_blobs'], [StorageUserAppendBlobResponse]);
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [StorageBatchGetAppendBlobsSingleResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageBatchGetAppendBlobsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageBatchGetAppendBlobsResponse</code>.
     */
    static validateJSON(data) {
        if (data['append_blobs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['append_blobs'])) {
                throw new Error("Expected the field `append_blobs` to be an array in the JSON data but got " + data['append_blobs']);
            }
            // validate the optional field `append_blobs` (array)
            for (const item of data['append_blobs']) {
                StorageUserAppendBlobResponse.validateJSON(item);
            };
        }
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                StorageBatchGetAppendBlobsSingleResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:snapser-apis/StorageUserAppendBlobResponse>} append_blobs
 */
StorageBatchGetAppendBlobsResponse.prototype['append_blobs'] = undefined;

/**
 * @member {Array.<module:snapser-apis/StorageBatchGetAppendBlobsSingleResponse>} results
 */
StorageBatchGetAppendBlobsResponse.prototype['results'] = undefined;






export default StorageBatchGetAppendBlobsResponse;

