/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import StorageIncrementCounterRequest from './StorageIncrementCounterRequest.js';

/**
 * The StorageBatchIncrementCounterRequest model module.
 * @module snapser-apis/StorageBatchIncrementCounterRequest
 * @version cremebrulee: v1 SDK
 */
class StorageBatchIncrementCounterRequest {
    /**
     * Constructs a new <code>StorageBatchIncrementCounterRequest</code>.
     * @alias module:snapser-apis/StorageBatchIncrementCounterRequest
     */
    constructor() { 
        
        StorageBatchIncrementCounterRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageBatchIncrementCounterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StorageBatchIncrementCounterRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/StorageBatchIncrementCounterRequest} The populated <code>StorageBatchIncrementCounterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageBatchIncrementCounterRequest();

            if (data.hasOwnProperty('counters')) {
                obj['counters'] = ApiClient.convertToType(data['counters'], [StorageIncrementCounterRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageBatchIncrementCounterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageBatchIncrementCounterRequest</code>.
     */
    static validateJSON(data) {
        if (data['counters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['counters'])) {
                throw new Error("Expected the field `counters` to be an array in the JSON data but got " + data['counters']);
            }
            // validate the optional field `counters` (array)
            for (const item of data['counters']) {
                StorageIncrementCounterRequest.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:snapser-apis/StorageIncrementCounterRequest>} counters
 */
StorageBatchIncrementCounterRequest.prototype['counters'] = undefined;






export default StorageBatchIncrementCounterRequest;

