/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import StorageBatchSingleUpdateAppendBlobResponse from './StorageBatchSingleUpdateAppendBlobResponse.js';

/**
 * The StorageBatchUpdateAppendBlobResponse model module.
 * @module snapser-apis/StorageBatchUpdateAppendBlobResponse
 * @version cremebrulee: v1 SDK
 */
class StorageBatchUpdateAppendBlobResponse {
    /**
     * Constructs a new <code>StorageBatchUpdateAppendBlobResponse</code>.
     * @alias module:snapser-apis/StorageBatchUpdateAppendBlobResponse
     */
    constructor() { 
        
        StorageBatchUpdateAppendBlobResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageBatchUpdateAppendBlobResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StorageBatchUpdateAppendBlobResponse} obj Optional instance to populate.
     * @return {module:snapser-apis/StorageBatchUpdateAppendBlobResponse} The populated <code>StorageBatchUpdateAppendBlobResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageBatchUpdateAppendBlobResponse();

            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [StorageBatchSingleUpdateAppendBlobResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageBatchUpdateAppendBlobResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageBatchUpdateAppendBlobResponse</code>.
     */
    static validateJSON(data) {
        if (data['results']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['results'])) {
                throw new Error("Expected the field `results` to be an array in the JSON data but got " + data['results']);
            }
            // validate the optional field `results` (array)
            for (const item of data['results']) {
                StorageBatchSingleUpdateAppendBlobResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:snapser-apis/StorageBatchSingleUpdateAppendBlobResponse>} results
 */
StorageBatchUpdateAppendBlobResponse.prototype['results'] = undefined;






export default StorageBatchUpdateAppendBlobResponse;

