/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The StatisticsServiceIncrementUserStatisticBody model module.
 * @module snapser-apis/StatisticsServiceIncrementUserStatisticBody
 * @version cremebrulee: v1 SDK
 */
class StatisticsServiceIncrementUserStatisticBody {
    /**
     * Constructs a new <code>StatisticsServiceIncrementUserStatisticBody</code>.
     * @alias module:snapser-apis/StatisticsServiceIncrementUserStatisticBody
     * @param delta {Number} Value to increment the statistic by. Use negative to decrement
     */
    constructor(delta) { 
        
        StatisticsServiceIncrementUserStatisticBody.initialize(this, delta);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, delta) { 
        obj['delta'] = delta;
    }

    /**
     * Constructs a <code>StatisticsServiceIncrementUserStatisticBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StatisticsServiceIncrementUserStatisticBody} obj Optional instance to populate.
     * @return {module:snapser-apis/StatisticsServiceIncrementUserStatisticBody} The populated <code>StatisticsServiceIncrementUserStatisticBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsServiceIncrementUserStatisticBody();

            if (data.hasOwnProperty('delta')) {
                obj['delta'] = ApiClient.convertToType(data['delta'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsServiceIncrementUserStatisticBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsServiceIncrementUserStatisticBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StatisticsServiceIncrementUserStatisticBody.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

StatisticsServiceIncrementUserStatisticBody.RequiredProperties = ["delta"];

/**
 * Value to increment the statistic by. Use negative to decrement
 * @member {Number} delta
 */
StatisticsServiceIncrementUserStatisticBody.prototype['delta'] = undefined;






export default StatisticsServiceIncrementUserStatisticBody;

