/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import LeaderboardsIncrementScoreRequest from './LeaderboardsIncrementScoreRequest.js';

/**
 * The LeaderboardsBatchIncrementScoreRequest model module.
 * @module snapser-apis/LeaderboardsBatchIncrementScoreRequest
 * @version cremebrulee: v1 SDK
 */
class LeaderboardsBatchIncrementScoreRequest {
    /**
     * Constructs a new <code>LeaderboardsBatchIncrementScoreRequest</code>.
     * @alias module:snapser-apis/LeaderboardsBatchIncrementScoreRequest
     * @param incrementScoreRequests {Array.<module:snapser-apis/LeaderboardsIncrementScoreRequest>} List of requests with their scores to be incremented
     */
    constructor(incrementScoreRequests) { 
        
        LeaderboardsBatchIncrementScoreRequest.initialize(this, incrementScoreRequests);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, incrementScoreRequests) { 
        obj['increment_score_requests'] = incrementScoreRequests;
    }

    /**
     * Constructs a <code>LeaderboardsBatchIncrementScoreRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/LeaderboardsBatchIncrementScoreRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/LeaderboardsBatchIncrementScoreRequest} The populated <code>LeaderboardsBatchIncrementScoreRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeaderboardsBatchIncrementScoreRequest();

            if (data.hasOwnProperty('increment_score_requests')) {
                obj['increment_score_requests'] = ApiClient.convertToType(data['increment_score_requests'], [LeaderboardsIncrementScoreRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LeaderboardsBatchIncrementScoreRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LeaderboardsBatchIncrementScoreRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of LeaderboardsBatchIncrementScoreRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['increment_score_requests']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['increment_score_requests'])) {
                throw new Error("Expected the field `increment_score_requests` to be an array in the JSON data but got " + data['increment_score_requests']);
            }
            // validate the optional field `increment_score_requests` (array)
            for (const item of data['increment_score_requests']) {
                LeaderboardsIncrementScoreRequest.validateJSON(item);
            };
        }

        return true;
    }


}

LeaderboardsBatchIncrementScoreRequest.RequiredProperties = ["increment_score_requests"];

/**
 * List of requests with their scores to be incremented
 * @member {Array.<module:snapser-apis/LeaderboardsIncrementScoreRequest>} increment_score_requests
 */
LeaderboardsBatchIncrementScoreRequest.prototype['increment_score_requests'] = undefined;






export default LeaderboardsBatchIncrementScoreRequest;

