/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The StatisticsSetUserStatisticRequest model module.
 * @module snapser-apis/StatisticsSetUserStatisticRequest
 * @version cremebrulee: v1 SDK
 */
class StatisticsSetUserStatisticRequest {
    /**
     * Constructs a new <code>StatisticsSetUserStatisticRequest</code>.
     * @alias module:snapser-apis/StatisticsSetUserStatisticRequest
     * @param key {String} Name of the user statistic
     * @param userId {String} User ID of the user who's stats are being requested
     * @param value {String} Value to set the statistic to
     */
    constructor(key, userId, value) { 
        
        StatisticsSetUserStatisticRequest.initialize(this, key, userId, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, userId, value) { 
        obj['key'] = key;
        obj['user_id'] = userId;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>StatisticsSetUserStatisticRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StatisticsSetUserStatisticRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/StatisticsSetUserStatisticRequest} The populated <code>StatisticsSetUserStatisticRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsSetUserStatisticRequest();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsSetUserStatisticRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsSetUserStatisticRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StatisticsSetUserStatisticRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['user_id'] && !(typeof data['user_id'] === 'string' || data['user_id'] instanceof String)) {
            throw new Error("Expected the field `user_id` to be a primitive type in the JSON string but got " + data['user_id']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

StatisticsSetUserStatisticRequest.RequiredProperties = ["key", "user_id", "value"];

/**
 * Name of the user statistic
 * @member {String} key
 */
StatisticsSetUserStatisticRequest.prototype['key'] = undefined;

/**
 * User ID of the user who's stats are being requested
 * @member {String} user_id
 */
StatisticsSetUserStatisticRequest.prototype['user_id'] = undefined;

/**
 * Value to set the statistic to
 * @member {String} value
 */
StatisticsSetUserStatisticRequest.prototype['value'] = undefined;






export default StatisticsSetUserStatisticRequest;

