/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The StatisticsServiceSetUserStatisticBody model module.
 * @module snapser-apis/StatisticsServiceSetUserStatisticBody
 * @version cremebrulee: v1 SDK
 */
class StatisticsServiceSetUserStatisticBody {
    /**
     * Constructs a new <code>StatisticsServiceSetUserStatisticBody</code>.
     * @alias module:snapser-apis/StatisticsServiceSetUserStatisticBody
     * @param value {String} Value to set the statistic to
     */
    constructor(value) { 
        
        StatisticsServiceSetUserStatisticBody.initialize(this, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value) { 
        obj['value'] = value;
    }

    /**
     * Constructs a <code>StatisticsServiceSetUserStatisticBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StatisticsServiceSetUserStatisticBody} obj Optional instance to populate.
     * @return {module:snapser-apis/StatisticsServiceSetUserStatisticBody} The populated <code>StatisticsServiceSetUserStatisticBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsServiceSetUserStatisticBody();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsServiceSetUserStatisticBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsServiceSetUserStatisticBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StatisticsServiceSetUserStatisticBody.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

StatisticsServiceSetUserStatisticBody.RequiredProperties = ["value"];

/**
 * Value to set the statistic to
 * @member {String} value
 */
StatisticsServiceSetUserStatisticBody.prototype['value'] = undefined;






export default StatisticsServiceSetUserStatisticBody;

