/**
 * cremebrulee
 * Your custom SDK
 *
 * The version of the OpenAPI document: cremebrulee: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import StorageUpdateAppendBlobRequest from './StorageUpdateAppendBlobRequest.js';

/**
 * The StorageBatchUpdateAppendBlobRequest model module.
 * @module snapser-apis/StorageBatchUpdateAppendBlobRequest
 * @version cremebrulee: v1 SDK
 */
class StorageBatchUpdateAppendBlobRequest {
    /**
     * Constructs a new <code>StorageBatchUpdateAppendBlobRequest</code>.
     * @alias module:snapser-apis/StorageBatchUpdateAppendBlobRequest
     */
    constructor() { 
        
        StorageBatchUpdateAppendBlobRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StorageBatchUpdateAppendBlobRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:snapser-apis/StorageBatchUpdateAppendBlobRequest} obj Optional instance to populate.
     * @return {module:snapser-apis/StorageBatchUpdateAppendBlobRequest} The populated <code>StorageBatchUpdateAppendBlobRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageBatchUpdateAppendBlobRequest();

            if (data.hasOwnProperty('appendBlobs')) {
                obj['appendBlobs'] = ApiClient.convertToType(data['appendBlobs'], [StorageUpdateAppendBlobRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StorageBatchUpdateAppendBlobRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StorageBatchUpdateAppendBlobRequest</code>.
     */
    static validateJSON(data) {
        if (data['appendBlobs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['appendBlobs'])) {
                throw new Error("Expected the field `appendBlobs` to be an array in the JSON data but got " + data['appendBlobs']);
            }
            // validate the optional field `appendBlobs` (array)
            for (const item of data['appendBlobs']) {
                StorageUpdateAppendBlobRequest.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:snapser-apis/StorageUpdateAppendBlobRequest>} appendBlobs
 */
StorageBatchUpdateAppendBlobRequest.prototype['appendBlobs'] = undefined;






export default StorageBatchUpdateAppendBlobRequest;

